### DISCUSSION TITLE
How to add configuration of related resources to a stack

### DISCUSSION THREAD

**Discussion by unix** [nitrictech/nitric#315] [Q&A] [answered]
Hello guys 👐  We're using Nitric in production, deployed on the AWS. (works well, cool!)

Now we have an issue: sometimes we want to be able to change the `memory size` of a lambda, or the `maximum run time`, etc. (for [AWS Lambda configuration](https://docs.aws.amazon.com/lambda/latest/dg/configuration-function-common.html)) 
If we can do this in the `nitric-<stack>.yaml` file that would certainly be the most elegant solution, if not, is there any automated solution that would do this?

For users, when using other solutions, there are generally the following ways to change:
- Request [AWS API (UpdateFunctionConfiguration)](https://docs.aws.amazon.com/zh_cn/lambda/latest/dg/API_UpdateFunctionConfiguration.html#SSS-UpdateFunctionConfiguration-request-MemorySize)
- Add params to [aws-cdk](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-lambda-readme.html)
- [CloudFormation](https://docs.aws.amazon.com/zh_cn/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html) (`yaml` or `json`)

Thanks to everyone for each reply.

**Comment by asalkeld** [comment]
@unix we do have this issue: https://github.com/nitrictech/nitric/issues/245 to add function level configuration. It would probably make sense to be included in that.

**Comment by tjholm** [comment]
@unix glad you like it! 

This is definitely something we want to add to the framework :+1: and have been thinking through some ideas on the best way to implement this.

I think using the stack files would be elegant as they could contain configuration specific to each provider we support without introducing common abstractions between them.

I think it would be good for each function in a stack to be individually configurable with their own requirements as well, I'd like to get your thoughts on how you think this could be mapped. Using patterns like we do in the main `nitric.yaml` we could potentially allow conventional names for function files to determine runtime requirements.

Example stack file:
```yaml
name: aws
provider: aws
region: us-east-1
config: 
  # default function specs
  default:
    memory: 256
    timeout: 15
  # small function specs
  functions/*.sm.ts:
    memory: 128
    timeout: 10
  # medium function specs
  functions/*.md.ts:
    memory: 512
    timeout: 30
  # large function specs
  functions/*.lg.ts:
    memory: 1024
    timeout: 60
```
Another consideration is whether common configuration could be included as part of our application framework. This is less clean and comes with some quirks and challenges when abstracting between providers and setting different requirements by environment.

```typescript
import { config } from '@nitric/sdk';

config({
  memory: 128,
  timeout: 10
});
```

**Reply by unix** [reply]
Thanks for the reply, it's inspiring to see Nitric's progress.
Agree with you that it is elegant and generic to write a custom configuration to `nitric.yaml`.

**Reply by unix** [reply]
@tjholm 
Another question is, is there any roadmap for Nitric, as we are using Nitric in production and if this issue is not resolved anytime soon, we will have to migrate to another technology stack first.
No reproach or offense intended, just want to know the roadmap. If we can pay (or sponsor) for this issue to be resolved quickly, I'm sure we can work together as well.

**Reply by jyecusch** [reply]
Hey @unix, Sorry this is impacting your projects, I spoke with the team and we'll be able to start the work on this next week. We'll look to get a proposal and pre-release out over the next two weeks, which we'd love your feedback on.

Also, we have a roadmap we've been working on, talking to @tjholm we'll get that published somewhere public in the next week too. Again, suggestions and comments are welcome and would influence changes to that roadmap.

**Reply by asalkeld** [reply]
Here is a quick attempt at implementing what @tjholm suggested https://github.com/nitrictech/cli/pull/329

**Reply by unix** [reply]
Great to see the Nitric maintainers actively building this amazing product, cheers to you! ❤️ 
Nitric has a great developer experience and I'm sure more and more developers will start trying Nitric in the future, looking forward to each of your updates!

**Reply by asalkeld** [reply]
@unix https://github.com/nitrictech/cli/pull/329 has now been merged if you want to give develop branch a go..
It would be great to hear if that fixes your use case.
Thank you for the wonderful feedback! Let us know what else we can do to improve it :-)

**Reply by tjholm** [reply, marked as answer]
@unix This was released today in [v1.9.0](https://github.com/nitrictech/cli/releases/tag/v1.9.0) of the CLI. We still need to finalise documentation for this feature. 

The implementation is similar to the above with the exception that pattern matching is not implemented. So to set the memory and timeout of a specific function you need to give the path for the function:

For example:
```yaml
config: 
  # default function specs
  default:
    memory: 256
    timeout: 15
  # small function specs
  functions/hello-world.ts:
    memory: 128
    timeout: 10
```

Let us know if you encounter any issues with this, or if you have other configuration requirements for your resources.
