### ISSUE TITLE
Update Action Workflows to remove checkout token: ${{secrets.GOLANG_TOKEN}}

### ISSUE THREAD

**Issue by medgar-nitric** [nitrictech/nitric#127]
To enable Github security dependency analysis feature 'Dependabot' we need to remove the Github secrets tokens so Dependabot can run when making a PR with updated dependencies.

```
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.GOLANG_TOKEN}}
        submodules: recursive
```

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1dyn94r) by [Unito](https://www.unito.io)
