### ISSUE TITLE
nitric up (unable to find nitric-.yaml)

### ISSUE THREAD

**Issue by asibilia** [nitrictech/nitric#266]
**Describe the bug**
after running `nitric stack new` and going through the workflow, I get a new `nitric-dev.yaml` file with my configuration. Running `nitric up` results in this error: 

```
Error: no nitric stack found (unable to find nitric-.yaml). If you haven't created a stack yet, run `nitric stack new` to get started
```

**Expected behavior**

Deploys my project.

**To Reproduce**

run `nitric up`

**Output of `nitric info -o yaml`:**

```yaml
os: darwin
arch: amd64
goversion: go1.17.7
cliversion: was not built with version info
fabricversion: v0.15.0
containerruntime: docker
containerruntimeversion: |
  platform:
    name: Docker Desktop 4.7.1 (77678)
  components:
  - name: Engine
    version: 20.10.14
    details:
      ApiVersion: "1.41"
      Arch: amd64
      BuildTime: "2022-03-24T01:46:14.000000000+00:00"
      Experimental: "false"
      GitCommit: 87a90dc
      GoVersion: go1.16.15
      KernelVersion: 5.10.104-linuxkit
      MinAPIVersion: "1.12"
      Os: linux
  - name: containerd
    version: 1.5.11
    details:
      GitCommit: 3df54a852345ae127d1fa3092b95168e4a88e2f8
  - name: runc
    version: 1.0.3
    details:
      GitCommit: v1.0.3-0-gf46b6ba
  - name: docker-init
    version: 0.19.0
    details:
      GitCommit: de40ad0
  version: 20.10.14
  apiversion: "1.41"
  minapiversion: "1.12"
  gitcommit: 87a90dc
  goversion: go1.16.15
  os: linux
  arch: amd64
  kernelversion: 5.10.104-linuxkit
  experimental: false
  buildtime: "2022-03-24T01:46:14.000000000+00:00"
```

**Brief description of your project**

Just testing a simple serverless function deployment.

**Additional context**

If I change my file name to `nitric-.yaml` the `nitric up` command works as expected.
