### ISSUE TITLE
Building on ARM CPUs causes error on AWS

### ISSUE THREAD

**Issue by unix** [nitrictech/nitric#283]
**Describe the bug**

The example works fine locally, but when deployed to the AWS platform, the endpoint is not accessible. (I also tried using Pulumi or manually creating a lambda in AWS and adding a gateway, etc., and it worked fine.)

When I call the endpoint directly or try to test under AWS' Lambda test service, I see the following error in the log:

```
START RequestId: b478530d-bdfe-46e8-8006-70473b2f87ff Version: $LATEST
2022/05/19 05:54:58 Registered Gateway Plugin
2022/05/19 05:54:58 Starting Child Process
2022/05/19 05:54:58 Services listening on: 127.0.0.1:50051
2022/05/19 05:54:58 Membrane Error: there was an error starting the child process: fork/exec /usr/local/bin/ts-node: exec format error, exiting
2022/05/19 05:54:58 gateway 'Stop' called, waiting for lambda runtime to finish
END RequestId: b478530d-bdfe-46e8-8006-70473b2f87ff
REPORT RequestId: b478530d-bdfe-46e8-8006-70473b2f87ff	Duration: 15017.11 ms	Billed Duration: 15000 ms	Memory Size: 128 MB	Max Memory Used: 6 MB	
2022-05-19T05:55:13.417Z b478530d-bdfe-46e8-8006-70473b2f87ff Task timed out after 15.02 seconds
```

**Expected behavior**

Consistent results with local runs after deployment.

**To Reproduce**

1. Run `nitric new` to create project.
2. Run `nitric run` to check function on local. It works well here.
3. Run `nitric up -s <my-stack>` to deploy. No errors were generated and all resources were successfully deployed. In Pulumi's monitoring panel, I can see that every service is working properly.
4. Trigger `<endpoint>/hello/world`, get `Internal Server Error`.

**I've tried removing all resources and redeploying with the command and got the same result.**

**Output of `nitric info -o yaml`:**

```yaml
os: darwin
arch: arm64
goversion: go1.17.9
cliversion: was not built with version info
fabricversion: v0.15.1-rc.8
containerruntime: docker
containerruntimeversion: |
  platform:
    name: Docker Desktop 4.8.1 (78998)
  components:
  - name: Engine
    version: 20.10.14
    details:
      ApiVersion: "1.41"
      Arch: arm64
      BuildTime: "2022-03-24T01:45:44.000000000+00:00"
      Experimental: "false"
      GitCommit: 87a90dc
      GoVersion: go1.16.15
      KernelVersion: 5.10.104-linuxkit
      MinAPIVersion: "1.12"
      Os: linux
  - name: containerd
    version: 1.5.11
    details:
      GitCommit: 3df54a852345ae127d1fa3092b95168e4a88e2f8
  - name: runc
    version: 1.0.3
    details:
      GitCommit: v1.0.3-0-gf46b6ba
  - name: docker-init
    version: 0.19.0
    details:
      GitCommit: de40ad0
  version: 20.10.14
  apiversion: "1.41"
  minapiversion: "1.12"
  gitcommit: 87a90dc
  goversion: go1.16.15
  os: linux
  arch: arm64
  kernelversion: 5.10.104-linuxkit
  experimental: false
  buildtime: "2022-03-24T01:45:44.000000000+00:00"
```

**Brief description of your project**

Basic sample, create from `nitric new`.

**Additional context**
