### ISSUE TITLE
Design: Configurable Function Runtimes

### ISSUE THREAD

**Issue by tjholm** [nitrictech/nitric#383]
When deploying with a given provider a nitric project needs to be able to provide more specific instructions for a functions deployment (i.e. deploy to a given service runtime e.g. Lambda/ECS Fargate/Lightsail).

Additional Considerations:

- [ ] Add additional runtime specific configuration for functions (e.g. Provisioned concurrency for AWS lambda). Adding this consideration and these configuration options may be mutually exclusive across individual provider runtimes.

Acceptance Criteria:

- [ ] A design proposal that allows an individual function to be deployed to a given runtime for a provider.

**Comment by tjholm** [comment]
Example AWS configuration
```yaml
name: my-aws-stack
provider: nitric/aws@0.23.2
config: 
  # default function specs
  default:
    target: lambda
    memory: 256
    timeout: 15
  # TODO: Need a way to properly target a deployed function
  my-other-function:
    target: lightsail
    some-lightsail-property: ???
```

**Comment by jyecusch** [comment]
I could see categories of functions being useful too - e.g. 'small', 'medium', 'memory_optimized' - so it's quick to deploy a set of functions with similar hosting requirements. Should we consider changes to the `handlers` nitric.yaml property to match function types, then map those types to deployment configurations?

**Comment by raksiv** [comment]
Would be good to support customizable categories, so that the users can make them org specific if they want to tweak our defaults.

**Comment by tjholm** [comment]
@jyecusch Do you see these categories being universal for all providers, unique to specific providers or configured as part of the stack using provider specific configuration?

**Comment by jyecusch** [comment]
I imagine the grouping being provider agnostic (project level), but the configuration of that group as provider specific (e.g. a 'large' function could be configured differently for AWS and Azure based on what config they offer)

**Comment by jyecusch** [comment]
Concepts from our design discussion:

Allow for named groups/categories of handlers.

`nitric.yaml`

```yaml
name: diagram
handlers:
  - functions/*.ts
  - type: memory-optimized
    match: processing/*.ts
  - type: stateful
    match: services/*.ts
```

Map these named categories onto specific deployment targets and target configurations within stack files (allowing for provider and environment specific config).

`dev-nitric.yaml`

```yaml
name: develop
provider: aws
region: ap-southeast-2
config: 
  # default function specs
  default:
    target: lambda
    memory: 256
    timeout: 15
  # # TODO: Need a way to properly target a deployable function, currently names are inferred from files
  # # but dockerfiles should be different to ensure they're re-usable.
  stateful:
    target: lightsail
    memory: 1024
    some-lightsail-property: ???
  memory-optimized:
    target: fargate
    memory: 2048
    some-fargate-property: ???
```
