### ISSUE TITLE
Support Custom URLS

### ISSUE THREAD

**Issue by raksiv** [nitrictech/nitric#391]
Developers would like to be able to configure custom urls for apis instead of using the auto generated addresses.

**Comment by tjholm** [comment]
Currently looking at implementing this at the providers, starting with the AWS provider. Because URLs will be expected to differ between environments this will be stack level configuration.

Proposal for AWS configuration:

```yaml
name: my-aws-stack
provider: nitric/aws@0.30.0
region: ap-southeast-2

# Add a key for configuring apis
apis:
   # Target an API by its nitric name
   my-api-name:
      # provide a domain to be used for the api
      domain: test.example.com
```
Current assumptions for AWS is that the certificate for the domain will already be managed in ACM with a managed zone in route 53. Domains will be discovered by searching for the domain using the provided name to locate a valid certificate.
