### ISSUE TITLE
Config Document Suggestions

### ISSUE THREAD

**Issue by mal-drop** [nitrictech/nitric#466]
Some documentation observations:
* AWS lambdas were created with 128 MB RAM setting by default. However the general documentation indicates the default is 512 MB. https://nitric.io/docs/deployment
* need to add `vpc` content to the AWS https://nitric.io/docs/reference/providers/aws/configuration

```yaml
config:
  default:
    lambda:
      # only functions that require DB access should be in this VPC
      vpc:
        security-group-ids:
          - sg-xxxx
        subnet-ids:
          - subnet-xxx
          - subnet-xxx
```
