### ISSUE TITLE
docs: using nitric with azure pipelines

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#501]
We'd like to make it easier to get started building pipelines that include nitric. Let's create a guide on how to automatically deploy nitric projects from Git to Azure using the nitric CLI and Azure pipelines. The guide should live in the [docs repo](https://github.com/nitrictech/docs)

**Comment by raksiv** [comment]
https://www.pulumi.com/docs/using-pulumi/continuous-delivery/azure-devops/

**Comment by raksiv** [comment]
The most basic solution would just be to use scripts and not create a Azure extension. Can't test easily since we don't have azure credit.

```yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- script: |
    # Install Pulumi
    curl -fsSL https://get.pulumi.com | sh
    # Export path for pulumi (assuming default installation path)
    export PATH=$PATH:$HOME/.pulumi/bin
    pulumi version

    # Install Nitric
    curl https://nitric.io/install | bash
    nitric --version
  displayName: 'Install Pulumi and Nitric'
```
