### ISSUE TITLE
static port mapping for local development

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#560]
### Suggestion
Allow for API and other entrypoint ports to be set to static values based on the resource's name.

### Value
Allow local development which includes automated tests or UIs that interact with the APIs to be configured once, avoiding port changes when new APIs are added to existing projects.

**Comment by davemooreuws** [comment]
Just a note that this is implemented via an env var with http proxies.

**Comment by davemooreuws** [comment]
> @davemooreuws is there an example?

Hey @chimon2000, the http proxy one was done on the SDK level (for the node-sdk).

https://github.com/nitrictech/node-sdk/blob/6bc461c399c17177f9ce0c0454e0adfd40d292ed/src/resources/http.ts#L111

I think the feature request might be looking for something more generic and broad in the nitric yaml like: @jyecusch 

```yaml
ports:
  main: 4001
  private: 4002
```

**Comment by davemooreuws** [comment]
Finished, example config `local.nitric.yaml`:

```yaml
# local.nitric.yaml
# Local development configuration for Nitric services.

apis:
  # API Resources
  first-api:
    port: 6001

  second-api:
    port: 6002

  my-db-api:
    port: 6003

  my-secret-api:
    port: 6004

websockets:
  # WebSocket Resources
  socket:
    port: 7001

  socket-2:
    port: 7002

  socket-3:
    port: 7002
```
