### ISSUE TITLE
Local HTTPS support for APIs

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#637]
### Suggestion

> From Discord Support Chat

Currently developing MS office app addons these apps are side loaded into Excel, Word, Powerpoint. The office addins are served locally with SSL certs and require https connections. So at the moment our local nitric api is served over http which means our local office apps won't talk to the local dev server. 

Ideally: We have the option to set each service as https true for local development which will generate the SSL certs in the background automatically and serve the local env on https.

```yaml
name: excel-add-in

services:
    - match: services/*.ts
      start: npm run dev:services $SERVICE_PATH
      https: true
 ```

### Value

Enables local development of APIs, etc. that serve other tools/software that require https connections

### Alternatives

We deploy our api so that our local excel addin can make https requests to the deployed api gateway.
